update 0.1.40

diff --git a/.github/workflows/build-test.yml b/.github/workflows/build-test.yml
--- a/.github/workflows/build-test.yml
+++ b/.github/workflows/build-test.yml
@@ -145,7 +145,11 @@ jobs:
       run: |
         . ./activate
         cargo build
-        pip install .
+        # This finds and installs a compatible wheel from the target directory on linux.
+        # We do it here as a hedge against changes in the python environment that might
+        # have happened due to pulling in the trunk versions of other packages that
+        # depend on klvm_tools_rs.
+        pip install --no-index --find-links target/wheels/ klvm_tools_rs
         pip install klvm_rs
         pip install klvm_tools
         cd resources/tests && python test_klvm_step.py && python mandelbrot-cldb.py
@@ -280,6 +284,13 @@ jobs:
       with:
         name: wheels
         path: ./target/wheels/
+
+    - name: Check for incompatible wheels and bail if found
+      run: |
+        set -e
+        # Check for a wheel with -linux_x86_64 platform tag, which will
+        # fail uploading to pypi.
+        find target -name \*-linux_x86_64.whl -exec /bin/false '{}' '+'
 
     - name: Publish distribution to PyPI
       if: env.RELEASE == 'true'
